import streamlit as st
import os
import requests
import cv2
import pandas as pd
import numpy as np
from ultralytics import YOLO
from fpdf import FPDF
from PIL import Image

# --- 1. MODEL CONFIGURATION ---
MODEL_URL = "https://huggingface.co/elizpayasli/car_dd/resolve/main/best%20(3).pt"
MODEL_PATH = "best.pt"

@st.cache_resource
def download_and_load_model():
    if not os.path.exists(MODEL_PATH):
        with st.spinner("Downloading AI model, please wait..."):
            try:
                response = requests.get(MODEL_URL, stream=True)
                if response.status_code == 200:
                    with open(MODEL_PATH, "wb") as f:
                        for chunk in response.iter_content(chunk_size=1024*1024):
                            if chunk:
                                f.write(chunk)
                    st.success("Model loaded successfully!")
                else:
                    st.error(f"Download failed. Status code: {response.status_code}")
                    return None
            except Exception as e:
                st.error(f"Download error: {e}")
                return None
    return YOLO(MODEL_PATH)

# --- 2. PDF REPORT GENERATION ---
def create_pdf(df, total_cost):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    
    pdf.cell(200, 10, txt="Car Damage Assessment Report", ln=True, align='C')
    pdf.ln(10)
    
    # Table Headers
    pdf.set_font("Arial", "B", 12)
    pdf.cell(70, 10, "Damage Type", 1)
    pdf.cell(60, 10, "Confidence", 1)
    pdf.cell(60, 10, "Cost ($)", 1)
    pdf.ln()
    
    # Table Rows
    pdf.set_font("Arial", "", 12)
    for index, row in df.iterrows():
        pdf.cell(70, 10, str(row["Damage Type"]), 1)
        pdf.cell(60, 10, str(row["Confidence"]), 1)
        pdf.cell(60, 10, f"${row['Estimated Cost ($)']}", 1)
        pdf.ln()
        
    pdf.ln(10)
    pdf.set_font("Arial", "B", 14)
    pdf.cell(200, 10, txt=f"Total Repair Amount: ${total_cost:,.2f}", ln=True)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(200, 10, txt="This report was automatically generated by AI System.", ln=True)
    
    return pdf.output(dest='S').encode('latin-1', 'ignore')

# --- 3. UI CONFIGURATION ---
st.set_page_config(page_title="Car Damage AI", layout="wide")

with st.sidebar:
    st.markdown("# 👤 Developer")
    st.subheader("Eliz Payasli") 
    st.write("Boğaziçi University IE & CS Student")
    st.markdown("---")
    st.title("Project Info")
    st.info("AI-powered car damage analyzer providing instant cost estimations.")
   

st.title("🚗 AI Car Damage Analysis & Cost Estimation")
st.markdown("Upload a photo of the damaged vehicle to get an instant repair cost assessment.")

model = download_and_load_model()

# --- 4. PRICE DICTIONARY ---
price_dictionary = {
    'doorouter-dent': 150.0,
    'fender-dent': 120.0,
    'front-bumper-dent': 200.0,
    'Headlight-Damage': 350.0,
    'Front-Windscreen-Damage': 500.0,
    'doorouter-scratch': 50.0,
    'bonnet-dent': 250.0,
    'rear-bumper-dent': 180.0,
    'quaterpanel-dent': 100.0,
    'default': 100.0
}

# --- 5. MAIN LOGIC ---
if model:
    uploaded_file = st.file_uploader("Choose an image...", type=['jpg', 'jpeg', 'png'])

    if uploaded_file is not None:
        file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
        image = cv2.imdecode(file_bytes, 1)
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        with st.spinner('Analyzing damages...'):
            results = model.predict(source=image, conf=0.15)
            result = results[0]
        
        ann_image = image_rgb.copy()
        report_data = []

        for box in result.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cls_id = int(box.cls[0])
            raw_label = model.names[cls_id]
            prob = float(box.conf[0])
            
            # --- FORMATTING THE LABEL ---
            # Transforms 'doorouter-dent' to 'Doorouter Dent'
            clean_label = raw_label.replace("-", " ").title()
            
            cost = price_dictionary.get(raw_label, price_dictionary['default'])
            
            report_data.append({
                "Damage Type": clean_label, 
                "Confidence": f"{prob*100:.1f}%", 
                "Estimated Cost ($)": cost
            })

            # Draw Red Box and Clean Label on Image
            cv2.rectangle(ann_image, (x1, y1), (x2, y2), (255, 0, 0), 3)
            cv2.putText(ann_image, f"{clean_label} ${cost}", (x1, y1 - 10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 0, 0), 2)

        col1, col2 = st.columns([2, 1])

        with col1:
            st.subheader("Visual Analysis")
            st.image(ann_image, use_container_width=True)

        with col2:
            st.subheader("Assessment Details")
            if report_data:
                df = pd.DataFrame(report_data)
                st.dataframe(df, use_container_width=True)
                
                total_cost = df["Estimated Cost ($)"].sum()
                st.metric("Total Estimated Cost", f"${total_cost:,.2f}")
                
                pdf_bytes = create_pdf(df, total_cost)
                st.download_button(
                    label="📄 Download PDF Report",
                    data=pdf_bytes,
                    file_name="car_assessment_report.pdf",
                    mime="application/pdf",
                )
                
                st.write("---")
                st.bar_chart(df.set_index("Damage Type")["Estimated Cost ($)"])
            else:
                st.success("Perfect! No significant damage detected.")
else:
    st.error("System Error: AI Model could not be initialized.")
